name: flutter_vnc
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Goddchen/flutter-vnc
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dart_rfb:
    git:
      path: dart-rfb/
      ref: main
      url: https://github.com/Goddchen/dart-rfb
    # path: ../../dart-rfb/dart-rfb
  flutter:
    sdk: flutter
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
