name: PR workflow
on:
  - pull_request
jobs:
  flutter-rfb-analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - run: flutter pub get
      - run: flutter analyze --fatal-infos --fatal-warnings
  flutter-rfb-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - run: flutter format --output none --set-exit-if-changed .\lib\ .\test\
  flutter-rfb-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - run: flutter test
  example-analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - working-directory: example/
        run: flutter pub get
      - working-directory: example/
        run: flutter analyze --fatal-infos --fatal-warnings
  example-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - working-directory: example/
        run: flutter format --output none --set-exit-if-changed .\lib\ .\test\
  example-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
      - working-directory: example/
        run: flutter test
